Changed package version
The publishing workflow was unsuccessfull due to
the following error:

error: failed to push some refs to 'https://github.com/IT-Administrators/pymarkdownroh'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Next try with just a version change back to 0.0.1.